osquery: compile without system controls table
Now the whole compilation succeeds but libunwind.so.1 => not found.

If libunwind is included as a nativeBuildInput, compilation fails
with:

```
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: /build/source/build/osquery/config/libosquery_config.a(config.cpp.o): undefined reference to symbol '_Unwind_Resume@@GCC_3.0'
/nix/store/pmgnlnbygb95s4zc8sqhknz9sdz934pk-binutils-2.39/bin/ld: /nix/store/ynn1by1qdl16q6qwwh2h7zkgrn36c6i8-glibc-2.35-163/lib/libgcc_s.so.1: error adding symbols: DSO missing from command line
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>